import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidKotlinMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

/**
 * Compiles the JSON files in `src/commonTest/fixtures` into a Kotlin source
 * file, because `commonTest` has no multiplatform file API to read them at
 * runtime.
 *
 * A typed task with annotated inputs/outputs, not a `doLast { }` closure:
 * `org.gradle.configuration-cache=true` rejects a closure that captures
 * project state.
 */
abstract class GenerateJsonFixtures : DefaultTask() {
    @get:InputDirectory
    abstract val fixtureDir: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val sources = fixtureDir.get().asFile.listFiles()
            .orEmpty()
            .filter { it.isFile && it.name.endsWith(".json") }
            .sortedBy { it.name }
        check(sources.isNotEmpty()) {
            "no *.json fixtures found in ${fixtureDir.get().asFile}"
        }

        val target = outputDir.get().asFile
            .resolve("dev/dailysecuritynews/app/fixtures/JsonFixtures.kt")
        target.parentFile.mkdirs()

        val text = buildString {
            appendLine("// Generated by :shared:generateJsonFixtures. Do not edit.")
            appendLine("package dev.dailysecuritynews.app.fixtures")
            appendLine()
            appendLine("internal val JSON_FIXTURES: Map<String, String> = mapOf(")
            for (source in sources) {
                appendLine("    \"${source.name}\" to buildString {")
                // A JVM string literal cannot exceed 64 KB of UTF-8 and the
                // captured edition is 106 KB, so it is appended in chunks.
                for (chunk in source.readText().chunked(4000)) {
                    appendLine("        append(\"${escape(chunk)}\")")
                }
                appendLine("    },")
            }
            appendLine(")")
            appendLine()
            appendLine("internal fun jsonFixture(name: String): String =")
            appendLine("    JSON_FIXTURES[name] ?: error(\"no JSON fixture named \$name\")")
        }
        target.writeText(text)
    }

    /**
     * Escapes to pure ASCII: every non-ASCII character becomes `\uXXXX`, so a
     * chunk boundary falling between a surrogate pair is harmless. `$` is
     * load-bearing — the captured edition contains literal `$` characters and
     * an unescaped one is a Kotlin template expression.
     */
    private fun escape(chunk: String): String = buildString(chunk.length) {
        for (c in chunk) {
            when {
                c == '\\' -> append("\\\\")
                c == '"' -> append("\\\"")
                c == '$' -> append("\\$")
                c == '\n' -> append("\\n")
                c == '\r' -> append("\\r")
                c == '\t' -> append("\\t")
                c.code < 0x20 || c.code > 0x7E ->
                    append("\\u%04x".format(c.code))
                else -> append(c)
            }
        }
    }
}

val generateJsonFixtures = tasks.register<GenerateJsonFixtures>("generateJsonFixtures") {
    fixtureDir.set(layout.projectDirectory.dir("src/commonTest/fixtures"))
    outputDir.set(layout.buildDirectory.dir("generated/jsonFixtures/kotlin"))
}

kotlin {
    android {
        // Must differ from :androidApp's namespace — AGP requires each module's
        // Android namespace to be unique. :androidApp keeps the original
        // "dev.dailysecuritynews.app"; this library has no Android sources or
        // resources of its own, so its namespace only names an unused R class.
        namespace = "dev.dailysecuritynews.app.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        withHostTest {}

        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions {
                    jvmTarget.set(JvmTarget.JVM_11)
                }
            }
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.dependencies {
            api(compose.runtime)
            api(compose.foundation)
            api(compose.material3)
            api(compose.ui)
            api(compose.components.resources)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.okio)
            implementation(libs.markdown.renderer.m3)
            // BackHandler ships in its own Compose Multiplatform artifact
            // rather than in compose.ui, so system back needs this on the
            // classpath even though everything else here comes from the
            // compose plugin's own accessors.
            implementation(libs.compose.ui.backhandler)
        }
        androidMain.dependencies {
            implementation(libs.ktor.client.okhttp)
        }
        iosMain.dependencies {
            implementation(libs.ktor.client.darwin)
        }
        commonTest {
            kotlin.srcDir(generateJsonFixtures.flatMap { it.outputDir })
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.ktor.client.mock)
            implementation(libs.okio.fakefilesystem)
            implementation(libs.kotlinx.coroutines.test)
            // Explicit rather than transitive: CitationMarkdownTest parses with
            // the same parser Markdown(...) uses, so it must not depend on the
            // renderer's transitive graph staying as it is today.
            implementation(libs.jetbrains.markdown)
        }
    }
}
